language: ruby
sudo: false

rvm:
  - 2.5.3

before_install:
  - gem install bundler

install: bundle install --retry=3

before_script:
  - psql -c 'create database enbw_test;' -U postgres

services:
  - postgresql

notifications:
  email: false
