language: ruby
sudo: false

rvm:
  - 2.5.3
addons:
  postgresql: '9.6'

before_script:
- psql -c 'create database enbw_test;' -U postgres

install: bundle install --retry=3

notifications:
  email: false
