language: ruby
sudo: false

rvm:
  - 2.4.1
addons:
  postgresql: '9.6'

before_script:
- psql -c 'create database enbw_test;' -U postgres

before_install:
  - gem update --system
  - gem install bundler

install: bundle install --retry=3

notifications:
  email: false
